import type { PageGuideDefinition } from '../components/ui/PageGuide';

export const pageGuides: Record<string, PageGuideDefinition> = {
  dashboard: {
    eyebrow: 'SentinelOps Guide',
    title: 'Understanding the command overview',
    intro: 'This page is the fastest way to understand what is active in the current operational day, where pressure is building, and which checklist needs attention first.',
    sections: [
      { title: 'Operational State', body: 'The hero metrics summarize readiness, execution, containment, and staffing so you can assess the day at a glance.' },
      { title: 'Shift Radar', body: 'Each shift card shows how many operations are live, how many people are present, and whether the shift is moving smoothly.' },
      { title: 'Command Threads', body: 'These cards represent the current operational day\'s live checklists. Open one when you want full task-level progress and participation details.' },
      { title: 'Attention Queue', body: 'This panel surfaces the items most likely to need intervention, like missing coverage or active exceptions.' },
    ],
    workflow: [
      'Start with Operational State to understand the overall posture.',
      'Scan Shift Radar for any shift that is behind, understaffed, or carrying exceptions.',
      'Open the relevant command thread to work at checklist level.',
    ],
    tip: 'Use this page for awareness and prioritization. When you know where the issue is, move into the checklist or task workspace to act.',
  },
  checklist: {
    eyebrow: 'SentinelOps Guide',
    title: 'Working inside a checklist',
    intro: 'This workspace is built for live shift execution: join the checklist, work through the items, and keep supervisors aware of progress, exceptions, and handover details.',
    sections: [
      { title: 'Header Controls', body: 'The top bar holds checklist-wide actions such as joining, completing, exporting, and sharing the current operation.' },
      { title: 'Item Cards', body: 'Each item shows its current status and gives you the action path for starting work, updating progress, and handling substeps.' },
      { title: 'Sidebar Oversight', body: 'Progress, handover notes, and team participation are grouped on the right so operational context stays visible.' },
      { title: 'Completion and Export', body: 'Checklist completion closes the operation, while PDF export turns the current record into a shareable report.' },
    ],
    workflow: [
      'Join the checklist if you are participating in the shift.',
      'Work through the items from top to bottom, opening subitems when a task needs step-by-step execution.',
      'Use handover notes and team presence to keep the next operator or supervisor informed.',
    ],
    tip: 'Treat this page as the live source of truth for the shift. If it is not captured here, the rest of the team may not see it.',
  },
  checklists: {
    eyebrow: 'Timeline Guide',
    title: 'Browsing checklist history',
    intro: 'This page helps you search, filter, and review checklist runs across time so you can find a specific operation, compare shifts, or investigate past outcomes.',
    sections: [
      { title: 'Search and Filters', body: 'Use the search field and status or shift filters to narrow the list to the exact runs you care about.' },
      { title: 'Temporal Scope', body: 'Switch between all time, weekly, daily, or custom-range views when you want broad history or a tight operational slice.' },
      { title: 'Grouped Timeline', body: 'Runs are grouped by date so it is easier to read each day\'s operational story and spot gaps or spikes.' },
      { title: 'Delete Controls', body: 'Managers and admins can remove checklist instances when a run should no longer remain in the record.' },
    ],
    workflow: [
      'Choose the time window first so the list reflects the period you want to inspect.',
      'Apply status, shift, or keyword filters to narrow the timeline.',
      'Open a checklist instance to move from historical overview into full execution detail.',
    ],
    tip: 'Use weekly or date-range mode when you are reviewing patterns, and specific-day mode when you are tracing a known incident.',
  },
  templateManager: {
    eyebrow: 'Template Guide',
    title: 'Creating reusable checklist templates',
    intro: 'Templates define the structure of future checklist runs, so this page is where teams standardize what good execution looks like before a shift starts.',
    sections: [
      { title: 'Template Library', body: 'The list view is your reusable catalog of checklist blueprints for different shifts or operating routines.' },
      { title: 'Create and Edit', body: 'Authoring views let you shape checklist items, descriptions, and substeps before teams execute them live.' },
      { title: 'Template Briefing', body: 'The view mode shows the final structure exactly as operators are expected to follow it later.' },
      { title: 'Shift Fit', body: 'Each template can be aligned to a shift so the right structure is available at the right time.' },
    ],
    workflow: [
      'Start in the library to find an existing template or decide whether a new one is needed.',
      'Create or edit the structure so each item is clear, ordered, and practical for operators.',
      'Review the briefing view before handing the template to live operations.',
    ],
    tip: 'The best templates reduce hesitation. Write items the way operators naturally think and act during a shift.',
  },
  performance: {
    eyebrow: 'Performance Guide',
    title: 'Reading operational performance',
    intro: 'This page turns completed work into trends, rankings, and streaks so people can understand momentum over time instead of just today\'s snapshot.',
    sections: [
      { title: 'Timeframe Switcher', body: 'Change the lens between week, month, and quarter depending on whether you want recent movement or longer-term trends.' },
      { title: 'Your Performance', body: 'The top cards highlight your streak, total points, and completed shifts within the selected timeframe.' },
      { title: 'Charts and Leaderboards', body: 'These sections show how performance is moving and how users compare with one another.' },
      { title: 'Team Metrics', body: 'The summary cards on the right roll everything up into a wider team view of consistency and engagement.' },
    ],
    workflow: [
      'Choose the timeframe that matches the story you want to understand.',
      'Review your overview first, then compare it with the chart and leaderboard.',
      'Use team metrics to see whether personal results match the broader operational trend.',
    ],
    tip: 'Short windows show current momentum. Longer windows are better for judging sustained improvement.',
  },
  taskCenter: {
    eyebrow: 'Task Center Guide',
    title: 'Managing work in the task center',
    intro: 'The task center is for operational work that lives beyond a single checklist, from personal follow-ups to team and department assignments.',
    sections: [
      { title: 'Filter Lanes', body: 'The left-side filter options split your work into views like private tasks, assigned work, team tasks, overdue items, and completed items.' },
      { title: 'Command Hero', body: 'The top summary explains the current task picture with counts for visible, in-progress, overdue, and critical items.' },
      { title: 'Task Cards and Detail', body: 'Cards give a quick scan of title, owner, due date, and status. Open one to work with the full task detail view.' },
      { title: 'Create and Update', body: 'Managers and operators can create tasks, move statuses, and close work directly from this workspace.' },
    ],
    workflow: [
      'Pick the lane that matches the kind of work you need to see.',
      'Apply search, status, or priority filters when the queue is too broad.',
      'Open a task to update status, review history, or complete the work.',
    ],
    tip: 'Checklist pages are best for shift execution. Use Task Center when the work needs ownership and follow-through beyond a single run.',
  },
  userManagement: {
    eyebrow: 'Access Guide',
    title: 'Managing people and access',
    intro: 'This page is the control room for SentinelOps identities, helping administrators create users, assign roles, and maintain the right access for each team member.',
    sections: [
      { title: 'User Directory', body: 'The left panel lists everyone in the system and helps you search by name, username, or email.' },
      { title: 'Profile Editor', body: 'Selecting a user opens their editable profile so you can update role, department, section, status, or reset their password.' },
      { title: 'Create User', body: 'The create panel is where new accounts are set up with their basic identity, placement, and temporary password.' },
      { title: 'Role Meaning', body: 'Roles decide whether someone administers the platform, manages operations, or primarily executes day-to-day work.' },
    ],
    workflow: [
      'Search or select the person you want to manage.',
      'Review their current role, location, and account status before changing anything.',
      'Save updates or create a new user when a new operator joins the organization.',
    ],
    tip: 'Roles should match responsibility. Keeping access clean makes the rest of the platform easier and safer to use.',
  },
  advancedTeamManagement: {
    eyebrow: 'Scheduling Guide',
    title: 'Planning advanced team coverage',
    intro: 'This workspace is for managers shaping shift coverage over a selected period, balancing patterns, one-off assignments, and time-off exceptions.',
    sections: [
      { title: 'Date Presets', body: 'Quick presets jump you to tomorrow, the weekend, this month, or next month so you can plan the right horizon fast.' },
      { title: 'Coverage Snapshot', body: 'The summary metrics highlight how many assignments exist, how many people are covered, and where weekends or busy dates stand out.' },
      { title: 'Assignment Tools', body: 'Single assignment is for one person on one day, while bulk assignment applies a pattern across multiple people and dates.' },
      { title: 'Time Off Control', body: 'Registering days off explains expected absences so staffing plans remain realistic.' },
    ],
    workflow: [
      'Pick the section and date preset you want to manage.',
      'Review existing assignments before adding new ones.',
      'Use bulk patterns for repeatable schedules and time-off controls for exceptions.',
    ],
    tip: 'This page is strongest for planning and balancing coverage across a period, not for checking one operator\'s personal view.',
  },
  revampedTeamManagement: {
    eyebrow: 'Scheduling Guide',
    title: 'Navigating the modern team planner',
    intro: 'This version of the scheduler emphasizes multiple visual lenses so managers can inspect the same schedule as a calendar, timeline, or analytics view.',
    sections: [
      { title: 'View Modes', body: 'Calendar, timeline, and analytics each reveal different patterns in the same schedule data.' },
      { title: 'Preset Controls', body: 'Preset windows quickly change the planning horizon without making you enter dates manually.' },
      { title: 'Refresh and Sections', body: 'Refresh updates the data feed, while section selection helps admins move between teams.' },
      { title: 'Modal Actions', body: 'Assignment and time-off actions sit behind modal workflows so planning changes stay focused and deliberate.' },
    ],
    workflow: [
      'Choose the visual mode that fits your question: placement, sequencing, or trends.',
      'Adjust the preset and section until you are looking at the correct team window.',
      'Open the scheduling action you need once you understand the current coverage picture.',
    ],
    tip: 'If you are trying to explain staffing patterns to someone else, switch views first. Often the right lens is the difference between confusion and clarity.',
  },
  revolutionaryTeam: {
    eyebrow: 'Scheduling Guide',
    title: 'Using the grouped team view',
    intro: 'This page focuses on grouped schedule visibility, helping supervisors scan staffing by date and switch between grouped, list, and analytics perspectives.',
    sections: [
      { title: 'Grouped View', body: 'The main grouped calendar is designed for quick understanding of who is assigned and how coverage clusters together.' },
      { title: 'Search and Section Filters', body: 'Search narrows the visible data, and admins can switch sections to inspect different teams.' },
      { title: 'View Selector', body: 'Grouped, list, and analytics modes offer different ways to read the same scheduling data.' },
      { title: 'Quick Refresh', body: 'Use refresh when you want the latest schedule state without leaving the page.' },
    ],
    workflow: [
      'Start in grouped view for a broad coverage scan.',
      'Filter the data when you are hunting for a person, status, or section.',
      'Switch to another mode if you need a different perspective on the same roster.',
    ],
    tip: 'Grouped view is usually the fastest for spotting imbalances. Use analytics only after you know what pattern you want to explain.',
  },
  teamManagement: {
    eyebrow: 'Coverage Guide',
    title: 'Understanding team coverage',
    intro: 'This page is a calendar-driven view of section staffing, showing whether each date is fully covered, partially covered, or left without coverage.',
    sections: [
      { title: 'Month and Week Views', body: 'Use month mode for broad planning and week mode when you need a tighter operational horizon.' },
      { title: 'Coverage Indicators', body: 'Each day shows whether staffing is complete, partial, or missing so weak points stand out immediately.' },
      { title: 'Section and Preset Controls', body: 'Admins can move between sections, while presets quickly jump to common planning windows.' },
      { title: 'Summary Cards', body: 'The top-level counts help you understand how many shifts exist and how many dates are properly covered.' },
    ],
    workflow: [
      'Choose month or week view depending on how far ahead you need to look.',
      'Check the coverage indicators to spot problem days.',
      'Change the section or preset if you need to compare another team or timeframe.',
    ],
    tip: 'This page is best for spotting coverage gaps by date. Use the more advanced scheduling pages when you need to actively change assignments.',
  },
  databaseStats: {
    eyebrow: 'Telemetry Guide',
    title: 'Reading database health and growth',
    intro: 'This page translates backend storage telemetry into a simpler health picture so non-technical users can tell whether growth is steady, risky, or urgent.',
    sections: [
      { title: 'Health Summary', body: 'The main status cards explain whether the database is healthy, under warning pressure, or reaching a critical point.' },
      { title: 'Growth Chart', body: 'The chart shows daily movement so you can see whether storage is growing quickly, slowly, or even shrinking.' },
      { title: 'Control Notes', body: 'These notes turn raw storage figures into plain-language guidance about runway, capacity pressure, and growth pace.' },
      { title: 'Daily Ledger', body: 'The lower legend breaks the past seven days into individual entries for closer review.' },
    ],
    workflow: [
      'Check the current health status first.',
      'Look at the growth chart to understand the recent trend.',
      'Use the control notes and ledger when you want a plain-language explanation of what changed.',
    ],
    tip: 'You do not need to interpret the raw telemetry yourself. Focus on the status, runway, and whether the recent trend is stable or accelerating.',
  },
  networkSentinel: {
    eyebrow: 'Monitoring Guide',
    title: 'Watching service health in Network Sentinel',
    intro: 'This page tracks the live health of monitored services so teams can quickly spot outages, understand current impact, and investigate what changed.',
    sections: [
      { title: 'Service Inventory', body: 'The main list is your live monitoring board, with each service sorted by urgency so the worst issues rise first.' },
      { title: 'Filters and Search', body: 'Narrow the board by status, environment, group, or free-text search to focus on the right part of the network.' },
      { title: 'Outage Feed', body: 'The outage panel highlights active incidents so you can understand what is currently broken or degraded.' },
      { title: 'Investigation Mode', body: 'Selecting a service opens its deeper history, evidence rows, and export options for troubleshooting.' },
    ],
    workflow: [
      'Scan the service inventory for anything marked down or degraded.',
      'Select the affected service to understand its history and current reason.',
      'Use filters or CSV export when you need to isolate or share the evidence.',
    ],
    tip: 'Use the top-level board to detect, then the detail panel to investigate. Trying to troubleshoot from the full board alone is usually slower.',
  },
  trustlinkOperations: {
    eyebrow: 'Pipeline Guide',
    title: 'Following TrustLink operations',
    intro: 'This page follows the day\'s TrustLink processing pipeline from extraction through validation and file delivery so operators can tell what ran, what completed, and what still needs attention.',
    sections: [
      { title: 'Today Status', body: 'The hero metrics summarize stage completion, rows processed, total duration, and whether the export file is ready.' },
      { title: 'Pipeline Stages', body: 'Each stage represents a part of the processing run, making it easy to see where a run is currently blocked or complete.' },
      { title: 'Run History', body: 'Past runs are listed so you can inspect previous attempts, compare outcomes, and reopen older evidence.' },
      { title: 'Actions', body: 'Inspecting, refreshing, running, or downloading are all focused on understanding or controlling the current delivery flow.' },
    ],
    workflow: [
      'Check today\'s status card to see whether there is an active or completed run.',
      'Review the pipeline stages to identify where the process currently stands.',
      'Use run history when you need to inspect an earlier attempt or download a finished file.',
    ],
    tip: 'If a file is not ready, the stage view usually tells you why much faster than the history list alone.',
  },
  teamManagementCalendar: {
    eyebrow: 'Calendar Guide',
    title: 'Reading the team schedule calendar',
    intro: 'This page gives managers a section-level calendar of staffing so they can review coverage day by day without opening deeper planning tools.',
    sections: [
      { title: 'Calendar View', body: 'The embedded team calendar is the main workspace and shows how staffing coverage lands across the selected dates.' },
      { title: 'Coverage States', body: 'Dates communicate whether staffing is sufficient, partial, or absent so weak points stand out visually.' },
      { title: 'Section Scope', body: 'Admins can access broader section coverage, while non-admin managers are usually scoped to their own section.' },
      { title: 'Restricted Access', body: 'If you do not have the right role or section, the page explains that the team schedule is not available to you.' },
    ],
    workflow: [
      'Open the calendar and review the currently visible coverage window.',
      'Move through the dates to inspect upcoming problem periods.',
      'Switch to a more advanced team management page when you need to change assignments.',
    ],
    tip: 'Think of this as the viewing layer for team coverage, not the planning layer for building schedules from scratch.',
  },
  userScheduleDashboard: {
    eyebrow: 'Personal Schedule Guide',
    title: 'Understanding your schedule',
    intro: 'This page is the personal schedule view for an operator or manager, helping you see upcoming shifts, recovery days, and open days in one place.',
    sections: [
      { title: 'Month and Week Views', body: 'Month mode gives a broader planning picture, while week mode is better for immediate shift awareness.' },
      { title: 'Focus Day', body: 'Selecting a day reveals its status, timing, and details so you can understand exactly what is expected.' },
      { title: 'Upcoming Shift Panels', body: 'The side panels help you see your next assignment and the short list of upcoming shifts without scanning the full calendar.' },
      { title: 'Schedule Status', body: 'Days can be assigned, marked as recovery time, or left open when no shift has been scheduled yet.' },
    ],
    workflow: [
      'Open the page and check your next shift first.',
      'Switch between month and week depending on how far ahead you need to plan.',
      'Select specific dates when you want to confirm shift times or understand an open day.',
    ],
    tip: 'Open days do not always mean a mistake. They simply mean nothing has been assigned to you for that date yet.',
  },
  login: {
    eyebrow: 'Access Guide',
    title: 'Signing in to SentinelOps',
    intro: 'The login page is your entry point into the platform. It connects your account to the operational pages and limits what you can see based on your role.',
    sections: [
      { title: 'Email and Password', body: 'Enter the same account details created for your SentinelOps profile.' },
      { title: 'Sign In Action', body: 'Signing in opens the platform areas allowed for your role, such as dashboards, checklists, tasks, or management tools.' },
      { title: 'Error Messages', body: 'If sign-in fails, the page explains whether the problem looks like wrong credentials, connectivity issues, or a server problem.' },
      { title: 'Password Reset', body: 'The reset link is available when you cannot remember your current password.' },
    ],
    workflow: [
      'Enter your email address and password.',
      'Select Sign In and wait for the platform to confirm your access.',
      'Use the reset path if your password is no longer valid or accessible.',
    ],
    tip: 'If login errors mention connection problems, the issue may be the network or server rather than your account details.',
  },
  notFound: {
    eyebrow: 'Navigation Guide',
    title: 'Why you are seeing this page',
    intro: 'This page appears when SentinelOps cannot find the location you tried to open, usually because the link is outdated, incomplete, or typed incorrectly.',
    sections: [
      { title: 'Missing Destination', body: 'The page you requested is not available at the current address.' },
      { title: 'Return Home', body: 'The main action takes you back to the home area so you can restart from a valid page.' },
      { title: 'Broken Links', body: 'If you arrived here from another page, the original link may need updating.' },
      { title: 'Safe Recovery', body: 'Nothing is lost here. This page only helps you recover from a navigation dead end.' },
    ],
    workflow: [
      'Use the home button to return to a known working page.',
      'Navigate again from the main menu or dashboard.',
      'If this keeps happening from the same link, report that route as broken.',
    ],
    tip: 'A 404 page usually means the address is wrong, not that your account or data has disappeared.',
  },
};
