import type { PageGuideDefinition } from '../components/ui/PageGuide';

export const pageGuides: Record<string, PageGuideDefinition> = {
  dashboard: {
    eyebrow: 'Command Guide',
    title: 'Reading the operational command deck',
    intro: 'The dashboard is the lightest way to understand the current operational day. It pulls the live command picture into one deck so you can see posture, pressure, and action paths without hunting across multiple pages.',
    sections: [
      { title: 'Operational State', body: 'The hero metrics show readiness, execution, containment, and staffing so you can judge the day in seconds.' },
      { title: 'Shift Radar', body: 'Each shift panel shows staffing, active work, and whether the shift is running cleanly or starting to drift.' },
      { title: 'Command Threads', body: 'These cards represent today\'s active checklist threads. Open one when you need item-level progress, exceptions, or participant context.' },
      { title: 'Matrix and Actions', body: 'Use the matrix, attention queue, handover summary, and quick actions to move from awareness into the next operational step.' },
    ],
    workflow: [
      'Start with Operational State to understand the day\'s overall posture.',
      'Scan Shift Radar and the matrix for pressure, missing coverage, or stalled execution.',
      'Open the right command thread or use a quick action once you know where intervention is needed.',
    ],
    tip: 'This page is for command awareness. Once the issue is clear, shift into the checklist, task, or monitoring workspace to act with detail.',
  },
  checklist: {
    eyebrow: 'Execution Guide',
    title: 'Running a live checklist',
    intro: 'This is the live execution workspace for a shift. It is designed to keep action, coordination, and handover in one place so the checklist stays fast to work and easy to trust.',
    sections: [
      { title: 'Mission Controls', body: 'The header holds checklist-wide actions such as joining, completing, sharing, exporting, and exception-based completion.' },
      { title: 'Item Flow', body: 'Each card shows the current task state and gives the operator the right action path for starting, updating, or finishing work.' },
      { title: 'Smart Substeps', body: 'Items that break down into subitems open a guided execution path so detailed work does not overload the main checklist surface.' },
      { title: 'Oversight Rail', body: 'Progress, handover notes, and live participant presence stay visible on the right so supervisors and the next operator always have context.' },
    ],
    workflow: [
      'Join the checklist if you are actively participating in the shift.',
      'Work item by item, opening substeps when the task needs tighter execution detail.',
      'Keep handover notes and participation current, then complete or export once the run is stable.',
    ],
    tip: 'Treat this page as the operational source of truth. If execution, handover, or an exception is not captured here, the team cannot rely on it later.',
  },
  checklists: {
    eyebrow: 'Timeline Guide',
    title: 'Reviewing checklist history',
    intro: 'The checklists page is a grouped operational timeline. It helps you move quickly between today\'s coverage picture and deeper historical review without loading more than you need.',
    sections: [
      { title: 'Time Controls', body: 'Switch between all, week, day, and custom range modes to decide how wide or narrow the timeline should be.' },
      { title: 'Search and Filters', body: 'Search by keyword, then narrow further by status or shift when the history is too broad.' },
      { title: 'Timeline Clusters', body: 'Checklist runs are grouped by day so you can read each date as an operational story instead of a flat list.' },
      { title: 'Coverage and Record Actions', body: 'Today coverage gives quick shift awareness, while managers can still open or delete records when governance is required.' },
    ],
    workflow: [
      'Set the time mode first so the timeline reflects the slice you actually want to inspect.',
      'Apply search, shift, or status filters until the right runs are visible.',
      'Open the checklist instance you care about when you need full execution detail.',
    ],
    tip: 'Use week and range views to study patterns. Use day view when you are tracing a known event or handover.',
  },
  templateManager: {
    eyebrow: 'Template Guide',
    title: 'Authoring operational templates',
    intro: 'Templates define how future runs will feel in the field. This page is where teams shape clean, repeatable execution before the shift begins.',
    sections: [
      { title: 'Template Library', body: 'The library is the catalog of reusable checklist blueprints aligned to shifts, teams, and operating routines.' },
      { title: 'Builder Workspace', body: 'Create and edit modes let you structure the checklist, sequence work, and tune the operator experience before it goes live.' },
      { title: 'Rich Item Types', body: 'Templates can include standard items, timed steps, information blocks, scheduled events, conditional logic, and subitems.' },
      { title: 'Briefing View', body: 'View mode lets you inspect the final template as an operator-facing briefing before it becomes part of live execution.' },
    ],
    workflow: [
      'Start in the library to decide whether to reuse, refine, or create a template.',
      'Build the item flow so operators can move through it without hesitation.',
      'Review the briefing view before handing the template to a live shift.',
    ],
    tip: 'The best templates feel obvious under pressure. Write each item in the order and language operators naturally use during real work.',
  },
  performance: {
    eyebrow: 'Performance Guide',
    title: 'Reading the performance command deck',
    intro: 'The performance page is the SentinelOps gamification engine in full form. It blends checklist execution, task delivery, timed-start discipline, shared shift work, handover motion, and reliability into one command view so the score reflects real operational behavior instead of cosmetic activity.',
    sections: [
      { title: 'Window Summaries', body: 'Weekly, monthly, quarterly, and yearly cards each show how command points, grade, rhythm, and rank are moving at that horizon.' },
      { title: 'Operational Briefing', body: 'The active window breaks your score into execution, reliability, collaboration, and quality so you can see whether points came from real completions, timing discipline, or shared delivery.' },
      { title: 'Momentum and Feed', body: 'Trendline and recent wins help you connect the score back to real checklist work, task closures, and handover actions inside the selected window.' },
      { title: 'Badges and Ladder', body: 'Badges now cover shift specialties, collaborative shift work, timed-start discipline, and balanced command performance, while the leaderboard shows how you compare inside your visible SentinelOps scope.' },
    ],
    workflow: [
      'Choose the time window first so the right operational story is in focus.',
      'Read the briefing and score breakdown before looking at badges or rank.',
      'Use the trendline and recent feed to connect performance signals back to real work that happened in the system.',
    ],
    tip: 'Command points reward output, but late delivery and missed timed starts now drag the score down, so the strongest operators balance volume with discipline.',
  },
  taskCenter: {
    eyebrow: 'Task Center Guide',
    title: 'Running work from Task Center',
    intro: 'Task Center is the command lane for work that lives beyond a single checklist run. It keeps ownership, due dates, history, and follow-through visible without making the page feel heavy.',
    sections: [
      { title: 'Lane Control', body: 'The sidebar lanes split work into views such as personal, assigned, team, overdue, and completed so you can enter the right queue immediately.' },
      { title: 'Command Summary', body: 'The hero metrics show how many visible tasks need attention, which ones are active, and where urgency is building.' },
      { title: 'Detail and History', body: 'Open a task to work in the detail pane, then use the history flow when you need to understand what changed and when.' },
      { title: 'Task Actions', body: 'Create, update, and close work here when the job needs clear ownership beyond the life of a checklist.' },
    ],
    workflow: [
      'Choose the lane that matches the kind of work you need to manage.',
      'Apply search, status, or priority filters if the queue is still too broad.',
      'Open the task, act on it, and use history when you need change context before moving it forward.',
    ],
    tip: 'Use checklists for live shift execution. Use Task Center when the work needs persistence, accountability, and follow-up.',
  },
  userManagement: {
    eyebrow: 'Access Guide',
    title: 'Managing people and access',
    intro: 'User Management is the identity control room for SentinelOps. It is where administrators shape who can enter the platform, where they belong, and what level of responsibility they carry.',
    sections: [
      { title: 'User Directory', body: 'The directory lets you search people quickly by name, username, or email before moving into account work.' },
      { title: 'Profile Console', body: 'Selecting a user opens their editable identity record, including role, department, section, active state, and password controls.' },
      { title: 'Create User Flow', body: 'New accounts are created here with the person\'s core identity, organizational placement, and initial access setup.' },
      { title: 'Role and Placement', body: 'Roles shape platform authority, while department and section placement determine where users belong operationally.' },
    ],
    workflow: [
      'Find the person you need to manage in the directory.',
      'Review their current role, location, and account status before making changes.',
      'Save updates or create a new account when a new operator joins the organization.',
    ],
    tip: 'Keep access aligned to real responsibility. Clean identity structure makes every other SentinelOps workflow safer and easier to understand.',
  },
  advancedTeamManagement: {
    eyebrow: 'Scheduling Guide',
    title: 'Planning coverage with patterns',
    intro: 'This is the strongest scheduling workspace for managers shaping future coverage. It combines quick horizon controls, reusable shift patterns, and exception handling without losing sight of actual staffing pressure.',
    sections: [
      { title: 'Horizon Controls', body: 'Date presets such as tomorrow, weekend, this month, and next month let you jump to the planning window that matters.' },
      { title: 'Coverage Snapshot', body: 'The summary signals show assignment count, covered people, weekend pressure, and other indicators that reveal whether the plan is balanced.' },
      { title: 'Pattern Library and Rollout', body: 'Use stored patterns for repeatable schedules, then apply them in bulk when you need fast, consistent coverage placement.' },
      { title: 'Single Assignments and Time Off', body: 'Use one-off assignment and time-off actions to handle the real exceptions that patterns cannot cover cleanly.' },
    ],
    workflow: [
      'Choose the section and time horizon you want to plan.',
      'Read the current coverage picture before creating new assignments.',
      'Use patterns for repeatable structure and exceptions for the specific dates that need human judgment.',
    ],
    tip: 'Patterns create speed, but exceptions create realism. The best schedule is the one that reflects both.',
  },
  revampedTeamManagement: {
    eyebrow: 'Scheduling Guide',
    title: 'Switching between schedule lenses',
    intro: 'This planner is built around multiple ways of reading the same schedule. Use it when the team needs to understand placement, sequence, and broad staffing shape from different visual angles.',
    sections: [
      { title: 'View Modes', body: 'Calendar, timeline, and analytics each give a different lens on the same schedule so you can choose the clearest explanation for the moment.' },
      { title: 'Horizon and Section Scope', body: 'Preset date windows and section switching help you move quickly between planning horizons and team views.' },
      { title: 'Action Bar', body: 'Smart Assign, Single Shift, and Time Off actions are surfaced directly in the page so planning changes stay close to the schedule context.' },
      { title: 'Analytics Lens', body: 'Use analytics when you want to step back from individual dates and understand the broader staffing story.' },
    ],
    workflow: [
      'Choose the lens that best matches your question before changing the schedule.',
      'Set the section and preset so you are looking at the correct planning window.',
      'Open the action you need once the current coverage picture is clear.',
    ],
    tip: 'When a schedule feels confusing, the first fix is often a better lens rather than more data.',
  },
  revolutionaryTeam: {
    eyebrow: 'Scheduling Guide',
    title: 'Using the grouped schedule board',
    intro: 'This page centers on a grouped schedule view that makes staffing clusters easy to read. It is useful when you want quick visual understanding before reaching for deeper scheduling tools.',
    sections: [
      { title: 'Grouped Board', body: 'Grouped mode is the main working surface today and is the fastest way to scan assignments by date and team.' },
      { title: 'Search and Section Scope', body: 'Search narrows the visible roster, while admins can move between sections to inspect different teams.' },
      { title: 'Alternative Lenses', body: 'List and analytics are available as alternate views, but the grouped board remains the primary reading mode in the current experience.' },
      { title: 'Fast Actions', body: 'Refresh and the floating action path keep the page responsive when you want fresh schedule state or quick next steps.' },
    ],
    workflow: [
      'Start in grouped mode for the fastest coverage scan.',
      'Use search or section filters when you need to narrow the picture.',
      'Switch lenses only when you already know what pattern or person you are trying to examine.',
    ],
    tip: 'Grouped view is the clearest lens for most day-to-day staffing questions on this page right now.',
  },
  teamManagement: {
    eyebrow: 'Coverage Guide',
    title: 'Scanning staffing coverage',
    intro: 'This page is a lighter coverage-reading surface for managers. It shows whether dates are fully covered, partially covered, or exposed without pulling you into the heavier planning workflow.',
    sections: [
      { title: 'Coverage Summary', body: 'The top cards show total shifts and how many dates are fully covered, partially covered, or missing coverage.' },
      { title: 'Calendar Lenses', body: 'Switch between month and week views depending on whether you need broad planning context or a tighter operational horizon.' },
      { title: 'Day Signals', body: 'Each date is color-coded by coverage quality so weak points stand out immediately.' },
      { title: 'Scope and Navigation', body: 'Managers can move through the calendar window and admins can inspect different sections when needed.' },
    ],
    workflow: [
      'Choose month or week view based on how far ahead you need to assess.',
      'Scan the coverage colors to find exposed or partially staffed dates.',
      'Move the calendar window or switch section if you need to compare another period or team.',
    ],
    tip: 'Use this page to spot gaps. Use the advanced scheduling pages when you are ready to reshape assignments.',
  },
  databaseStats: {
    eyebrow: 'Telemetry Guide',
    title: 'Reading database runway',
    intro: 'Database Stats turns backend growth signals into a simpler runway story. It helps teams understand storage pressure, trend direction, and urgency without requiring database expertise.',
    sections: [
      { title: 'Capacity Forecast', body: 'The headline cards explain current size, projected pressure, days remaining, and the overall storage risk state.' },
      { title: 'Growth Pulse', body: 'Velocity and recent movement show whether growth is calm, accelerating, or beginning to look dangerous.' },
      { title: 'Growth Contour', body: 'The chart translates the recent trend into a visual shape so you can see whether the curve is flattening or steepening.' },
      { title: 'Ledger and Notes', body: 'Control notes and the daily ledger convert raw telemetry into practical language about what changed and what to watch next.' },
    ],
    workflow: [
      'Check the risk state and runway first.',
      'Read the growth pulse and contour to understand recent direction.',
      'Use the notes and ledger when you want the clearest plain-language explanation of the trend.',
    ],
    tip: 'You do not need to decode raw database metrics yourself. Focus on runway, growth direction, and whether the pressure is stable or accelerating.',
  },
  networkSentinel: {
    eyebrow: 'Monitoring Guide',
    title: 'Running the Network Sentinel command center',
    intro: 'This page is the live network operations deck for SentinelOps. It keeps the board light by separating fleet posture from focused investigation, while still preserving the evidence and major events you need for diagnosis.',
    sections: [
      { title: 'Command Center', body: 'The service grid is the live fleet view. Use it to spot which assets are up, degraded, or down without opening deeper diagnostics first.' },
      { title: 'Filters and Focus', body: 'Search plus status, environment, and group filters help you narrow the board quickly before you open a focused investigation.' },
      { title: 'Signal, Timeline, Evidence', body: 'Selecting a service opens a right-side investigation deck with sampled signal, major events, outage ledger, and retained raw evidence.' },
      { title: 'Retention Model', body: 'Raw evidence is kept short for space efficiency, while major events, outages, and sampled history stay longer so older incidents remain diagnosable.' },
    ],
    workflow: [
      'Scan the command center for any service marked degraded or down.',
      'Select the affected service and start in Signal to judge stability, then move to Timeline and Evidence for context.',
      'Use manual check, filters, or the evidence TXT export only after you know which asset you are investigating.',
    ],
    tip: 'Treat the left side as detection and the right side as diagnosis. Staying disciplined about that flow keeps the page fast and makes investigations much easier to read.',
  },
  trustlinkOperations: {
    eyebrow: 'Pipeline Guide',
    title: 'Following TrustLink operations',
    intro: 'TrustLink Operations is the run deck for the extraction pipeline. It is built to make today\'s processing state, file readiness, and older run evidence easy to read without drowning the operator in backend detail.',
    sections: [
      { title: 'Run State', body: 'The hero metrics summarize pipeline completion, rows processed, run duration, and whether the export is ready for delivery.' },
      { title: 'Pipeline Timeline', body: 'The stage view shows how the run is moving from extraction through validation, export, download readiness, and final delivery state.' },
      { title: 'Evidence Panel', body: 'Use the active run detail to inspect the selected run, understand what happened, and see where a failure or stall belongs in the sequence.' },
      { title: 'History and Controls', body: 'Run history, refresh, run now, download, overwrite, and file deletion actions give operators both visibility and deliberate control.' },
    ],
    workflow: [
      'Check the hero state to understand whether today\'s run is active, complete, or stuck.',
      'Read the pipeline timeline to identify the exact stage where movement stopped or succeeded.',
      'Use the evidence card and history list when you need to inspect a specific run or deliver the finished output.',
    ],
    tip: 'The pipeline timeline usually explains failure faster than the history list alone. Start there before taking action.',
  },
  teamManagementCalendar: {
    eyebrow: 'Calendar Guide',
    title: 'Reading the section schedule calendar',
    intro: 'This page is the clean viewing layer for section staffing. It keeps attention on coverage itself so managers can inspect the calendar without dropping into heavier scheduling tools.',
    sections: [
      { title: 'Calendar Surface', body: 'The embedded schedule calendar is the main workspace and shows how staffing lands across the visible date window.' },
      { title: 'Coverage Meaning', body: 'Each date communicates whether staffing is strong, partial, or missing so weak points stand out visually.' },
      { title: 'Section Scope', body: 'Admins can inspect broader section coverage, while other managers are usually limited to the section they own.' },
      { title: 'Access Guardrails', body: 'If the schedule is unavailable for your role or section, the page explains that clearly instead of exposing empty data.' },
    ],
    workflow: [
      'Open the page and read the currently visible calendar window.',
      'Move across upcoming dates to locate weak periods or upcoming strain.',
      'Switch to an advanced scheduling page when you need to change assignments rather than just inspect them.',
    ],
    tip: 'Think of this page as the viewing deck for coverage, not the authoring deck for building schedules.',
  },
  userScheduleDashboard: {
    eyebrow: 'Personal Schedule Guide',
    title: 'Reading your personal schedule deck',
    intro: 'This page gives each operator or manager a clear personal schedule picture, combining assigned shifts, recovery time, open days, deadlines, and upcoming work in one place.',
    sections: [
      { title: 'Summary Signals', body: 'The top summary gives you a fast read on your current schedule posture before you move into specific dates.' },
      { title: 'Calendar and Agenda', body: 'Use the month grid for broad visibility or switch to the weekly agenda when you need a tighter short-range view.' },
      { title: 'Focus Day and Deadlines', body: 'Selecting a day reveals its schedule state, timing, and any task deadlines linked to that date.' },
      { title: 'Upcoming Lineup', body: 'The side panels keep your next assignments and near-term sequence visible without forcing you to scan the whole calendar.' },
    ],
    workflow: [
      'Start with the summary and your next assignment to understand immediate expectations.',
      'Switch between month and week depending on how far ahead you need to plan.',
      'Select a date when you want exact shift detail, deadline context, or confirmation that a day is still open.',
    ],
    tip: 'An open day does not always mean a problem. It simply means nothing has been assigned to you for that date yet.',
  },
  login: {
    eyebrow: 'Access Guide',
    title: 'Signing in to SentinelOps',
    intro: 'The login page is the entry gate into SentinelOps. It now adapts to the authentication mode in front of you so people can tell whether they are signing in with Active Directory or SentinelOps credentials.',
    sections: [
      { title: 'Identity Mode', body: 'The form explains whether you should use your Windows credentials or your SentinelOps account details for this environment.' },
      { title: 'Directory Status', body: 'The Active Directory status panel shows whether directory-backed authentication is currently reachable and healthy.' },
      { title: 'Sign-In Result', body: 'Successful login opens the parts of SentinelOps your role allows, from dashboards and checklists to management pages.' },
      { title: 'Failure Signals', body: 'If sign-in fails, the page helps distinguish bad credentials from a server, directory, or connectivity issue.' },
    ],
    workflow: [
      'Check the sign-in hint so you know which credentials this environment expects.',
      'Review the directory status if the page is using Active Directory.',
      'Submit your credentials and follow the returned error signals if access is denied.',
    ],
    tip: 'When the page points to directory or connectivity trouble, the problem may be infrastructure rather than your credentials.',
  },
  notFound: {
    eyebrow: 'Navigation Guide',
    title: 'Recovering from a dead route',
    intro: 'This page appears when SentinelOps cannot resolve the address you tried to open. Usually the route is outdated, incomplete, or no longer belongs to the current application state.',
    sections: [
      { title: 'Missing Destination', body: 'The requested location does not exist at the current address.' },
      { title: 'Safe Return Path', body: 'The primary action takes you back to a known working area so you can re-enter the platform cleanly.' },
      { title: 'Broken Link Signal', body: 'If you arrived here from inside SentinelOps, the original link or route probably needs updating.' },
      { title: 'No Data Loss', body: 'This is only a navigation dead end. It does not mean your account, shift, or records have disappeared.' },
    ],
    workflow: [
      'Use the return action to get back to a known working page.',
      'Navigate again from the main menu, dashboard, or another trusted starting point.',
      'Report the route if the same broken path keeps sending you back here.',
    ],
    tip: 'A not-found page usually means the address is wrong, not that the underlying SentinelOps data is gone.',
  },
};
